version: "3.11"

services:
  api:
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - "./api/src:/src"
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
      - redis
    # in production environment variables should be in .env file
    # but for purpose of easier setup i decided to hardcode them here
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DATABASE_PORT=5432
      - DB_PASS=devpass
      # redis env variables
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=dev_redispass
      # celery env variables
      - CELERY_BROKER_URL=redis://:dev_redispass@redis:6379
      - CELERY_RESULT_BACKEND=redis://:dev_redispass@redis:6379
  celery_worker:
    build:
      context: ./api
      args:
        - DEV=true
    volumes:
      - "./api/src:/src"
    command: celery -A src worker -l INFO -P threads
    depends_on:
      - db
      - redis
      - api
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DATABASE_PORT=5432
      - DB_PASS=devpass
      # redis env variables
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=dev_redispass
      # celery env variables
      - CELERY_BROKER_URL=redis://:dev_redispass@redis:6379
      - CELERY_RESULT_BACKEND=redis://:dev_redispass@redis:6379
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass dev_redispass

volumes:
  dev-db-data:
    driver: local
